---
  apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nitro-backend
    namespace: human-connection
    commit: <COMMIT>
  spec:
    replicas: 1
    minReadySeconds: 15
    progressDeadlineSeconds: 60
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: "100%"
    selector:
      matchLabels:
        human-connection.org/selector: deployment-human-connection-backend
    template:
      metadata:
        labels:
          human-connection.org/selector: deployment-human-connection-backend
        name: "nitro-backend"
      spec:
        containers:
        - name: nitro-backend
          image: humanconnection/nitro-backend:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 4000
          envFrom:
          - configMapRef:
            name: configmap
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: human-connection
                key: JWT_SECRET
                optional: false
          env:
          - name: PRIVATE_KEY_PASSPHRASE
            valueFrom:
              secretKeyRef:
                name: human-connection
                key: PRIVATE_KEY_PASSPHRASE
                optional: false
          volumeMounts:
            - mountPath: /nitro-backend/public/uploads
              name: uploads
        volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: uploads-claim
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
  status: {}
---
  kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: uploads-claim
    namespace: human-connection
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
