apiVersion: v1
kind: Secret
data:
  JWT_SECRET: "Yi8mJjdiNzhCRiZmdi9WZA=="
  MONGODB_PASSWORD: "TU9OR09EQl9QQVNTV09SRA=="
  PRIVATE_KEY_PASSPHRASE: "YTdkc2Y3OHNhZGc4N2FkODdzZmFnc2FkZzc4"
metadata:
  name: human-connection
  namespace: human-connection
